title: "BaboonLand Dataset: Tracking Primates in the Wild and Automating Behaviour Recognition from Drone Videos"
description: "Isla Duporge, Maksim Kholiavchenko, Roi Harel, Scott Wolf, Dan Rubenstein, Tanya Berger-Wolf, Meg Crofoot, Stephen Lee, Julie Barreau, Jenna Kline, Michelle Ramirez, Charles Stewart"
theme: jekyll-theme-cayman
